#+TITLE: Introduction to Matrix Algebra-III
#+DATE: \today
#+LANGUAGE: en
#+OPTIONS: toc:nil
#+LATEX_CLASS: article
#+LATEX_COMPILER: xelatex -shell-escape

#+LATEX_HEADER: \usepackage{fontspec}
#+LATEX_HEADER: \setmainfont{TeX Gyre Pagella}
#+LATEX_HEADER: \usepackage{amsmath,amssymb,caption, gensymb, subcaption, tfrupee, tikz, xcolor}
#+LATEX_HEADER: \usepackage[backend=biber,style=authoryear-comp]{biblatex}
#+LATEX_HEADER: \addbibresource{references.bib}
#+LATEX_HEADER: \usepackage{geometry}
#+LATEX_HEADER: \geometry{margin=1in}
#+LATEX_HEADER: \usetikzlibrary{arrows.meta,patterns,positioning}
#+LATEX_HEADER: \definecolor{cbblue}{rgb}{0.0, 0.6, 0.9}
#+LATEX_HEADER: \definecolor{cbcyan}{rgb}{0.35, 0.7, 0.9}
#+LATEX_HEADER: \definecolor{cbred}{rgb}{0.8, 0.4, 0.0}
#+LATEX_HEADER: \definecolor{cbpurple}{rgb}{0.6, 0.6, 0.8}
#+LATEX_HEADER: \definecolor{cbolive}{rgb}{0.6, 0.7, 0}


** Transpose of a Matrix

Let $A$ be an $m\times{n}$. We define a new matrix denoted by $A^{T}$ which contains all the elements from $A$ except that the rows and the columns are interchanged. Therefore, the dimension of $A^{T}$ is $n\times{m}$.

An example:
\[ A = \begin{bmatrix} 1 & 2 & 3 \end{bmatrix}\]

$dim(A) = 1\times{3}$

\[ A^T = \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix} \]

$dim(A^T) = 3\times{1}$


*** Properties of Transpose
\begin{itemize}

\item[1] $(A^T)^{T} = A$ (the transpose of the transpose of a matrix is the original matrix).

\item[2] $(A^T + B^T) = (A + B)^{T}$.

\item[3] For any scalar $k$, $(kA)^{T} = kA^{T}$.

\item[4] For any two matrices $A$ and $B$ such that matrix multiplication is possible, $(AB)^{T} = B^T\times{A^T}$.

\end{itemize}

** Determinant of a Matrix

For any $n\times{n}$ (square) matrix $A$, there exists a unique number called the determinant of a matrix. It usually denoted by $det A$ or $|A|$.
Please note that determinants are defined only for square matrices.

*** Determinant of a $1\times{1}$ Matrix
If $A$ is a $1\times{1}$ matrix with its element $a$, the determinant of the matrix is $a$.

*** Determinant of a $2\times{2}$ Matrix

Let there be a $2\times{2}$ matrix
\[A = \begin{bmatrix} a & b \\ c & d \end{bmatrix}\]

Then, the determinant of $A$ is $ad - bc$.

An example:

\[ A = \begin{bmatrix} 1 & 2 \\ 3 & -1 \end{bmatrix}\]

$|A| = 1\times{1} - (2\times{3}) = -7$.

*** Determinant of a $3\times{3}$ Matrix

While we did not cover this case in the lecture, it is important to know how to compute the determinant of a $3\times{3}$ matrix.

Let
\[ A = \begin{bmatrix} a & b & c \\ d & e & f \\ g & h & i \end{bmatrix} \]

\[ |A| = a\times\begin{vmatrix} e & f \\ h & i \end{vmatrix} - b\times\begin{vmatrix} d & f \\ g & i \end{vmatrix} + c\times\begin{vmatrix} d & e \\ g & h \end{vmatrix} \]

This is just one of the ways to calculate the determinant of a $3\times{3}$ matrix. You can actually pick any particular row or column and construct second order determinants by deleting the elements along the row and the column.





** Inverse of a Matrix

We will stick to $2\times{2}$ case for the inverse of the matrix. We will begin with some rules.

1. A square matrix $A$ is said to be singular if $|A| = 0$ and non-singular if $|A| \neq 0$.

2. For two matrices $A$ and $B$, the determinant of the product of the matrices will be equal to the product of the determinants of the two matrices.
   $|AB| = |A|\times|B|$.

\textbf{Definition:} A square matrix $A$ is \textit{invertible} or \textit{non-singular} if there exists another matrix $B$ such that
\[ AB = BA = I \]

We call this matrix $B$ the inverse of the matrix $A$.

The inverse of a non-singular matrix $A$, denoted by $A^{-1}$, is defined as:
\[ A^{-1} = \frac{adj(A)}{|A|} \]

where $adj(A)$ is known as the adjoint matrix of $A$.

A square matrix $A$ is invertible if and only if $A$ is a non-singular matrix.

We already know $|A|$. Let's understand how to construct the adjoint matrix. As promised, we only consider a $2\times{2}$ matrix.

Let \[ A = \begin{bmatrix} a & b \\ c & d \end{bmatrix} \]

Then, \[ adj(A) = \begin{bmatrix} d & -b \\ -c & a \end{bmatrix} \]

So, the adjoint matrix, $adj(A)$, of a $2\times{2}$ matrix, $A$,  can be generated by switching the diagonal elements and changing the signs of the non-diagonal elements.

An example:

\[ A = \begin{bmatrix} 1 & 2 \\ 3 & 4\end{bmatrix}  \]


\[\implies  adj(A) = \begin{bmatrix} 4 & -2 \\ -3 & 1 \end{bmatrix} \]


Let's extend this example to compute $A^{-1}$.

\begin{align*}
A^{-1} &= \frac{adj(A)}{|A|} \\ |A| &= 1\times{4} - 2\times{3} = -2 \\
A^{-1} &= \frac{1}{-2}\begin{bmatrix} 4 & - 2 \\ -3 & 1 \end{bmatrix} \tag{since we already know $adj(A)$.} \\
A^{-1} &= \begin{bmatrix} \dfrac{-1}{2}\times 4 & \dfrac{-1}{2}\times(-2) \\[6pt] \dfrac{-1}{2}\times(-3) & \dfrac{-1}{2}\times{1} \end{bmatrix} \tag{this step follows the rule of scalar multiplication} \\
A^{-1} &= \begin{bmatrix} -2 & 1 \\[6pt] \dfrac{3}{2} & \dfrac{-1}{2} \end{bmatrix}
\end{align*}

** Linear Equations & Matrices

*** Basics

Let's take a step back and think of a system of linear equations. Consider the following set of equations:
\begin{align*}
2x + y &= 4 \\
x - 2y &= -3 
\end{align*}

We can represent this equation  (or any other set of equations) in the matrix form.
Let's define a few matrices to do this. Let $A$ be the matrix containing the coefficients on the variables, $X$ be the column vector  containing the unknowns, and $B$ be the column vector containing the constants.
We can write $AX = B$. In our example,
\begin{align*}
A &= \begin{bmatrix} 2 & 1 \\ 1 & - 2 \end{bmatrix} \\
X &= \begin{bmatrix} x \\ y \end{bmatrix} \\
B &= \begin{bmatrix} 4 \\ -3 \end{bmatrix}
\end{align*}

A general structure, given $n$ variables,  would be as follows: $A$ will be an $n\times{n}$ matrix, $X$ and $B$ two column vectors of dimension $n\times{1}$.  
We can solve these equations using matrix algebra. There are two ways to do this. Before we get into these methods, it is important to understand the different types of solutions. A linear system of equations can have exactly one solution (a unique solution) or  infinite solutions or no solution.

Given a matrix equation $A\times{X} = B$,
\begin{itemize}
\item When $|A| \neq 0$, there exists a unique solution.
\item When $|A| = 0$, it can either mean infinitely many solutions or no solutions.
     \begin{itemize}
     \item If $adj(A)\times{B}$ is not a zero matrix, then we have no solution.
     \item If $adj(A)\times{B}$ is a zero matrix, we may have infinitely many solutions.
     \end{itemize}
\end{itemize}

*** Matrix Inverse Method
Let's consider a two-variables two-equation system $AX = B$, where $A$, $X$ and $B$ have already been defined above.
We can show that $X = (A^{-1})\times{B}$.
\begin{align*}
AX &= B \\
(A^{-1})AX &= (A^{-1})\times{B} \tag{multiplying $A^{-1}$ to both sides} \\
(A^{-1}A)X &= A^{-1}\times{B}   \tag{since we know that matrix multiplication is associative} \\
IX &= A^{-1}\times{B}           \tag{since $A^{-1}\times{A} = I$} \\
X &= A^{-1}\times{B}            \tag{multiplying identity matrix to a matrix yields the matrix itself}
\end{align*}


An example: We have a set of equations in $x$ and $y$.
\begin{align*}
2x + y &= 4 \\
x - 2y &= -3 
\end{align*}

Let's write down all the matrices.
\begin{align*}
A &= \begin{bmatrix} 2 & 1 \\ 1 & - 2 \end{bmatrix} \\
X &= \begin{bmatrix} x \\ y \end{bmatrix} \\
B &= \begin{bmatrix} 4 \\ -3 \end{bmatrix}
\end{align*}

We are all set to apply the matrix inverse method to solve for $x$ and $y$. We will first need $A^{-1}$.
\begin{align*}
A &= \begin{bmatrix} 2 & 1 \\ 1 & -2 \end{bmatrix} \\
|A| &= 2\times{-2} - (1\times{1}) = -5 \\
adj(A) &= \begin{bmatrix} -2 & -1 \\ -1 & 2 \end{bmatrix} \\
A^{-1} &= \frac{-1}{5}\begin{bmatrix} -2 & -1 \\ -1 & 2 \end{bmatrix} \\
A^{-1} &= \begin{bmatrix} \dfrac{-1}{5}\times{-2} & \dfrac{-1}{5}\times{-1} \\[6pt] \dfrac{-1}{5}\times{-1} & \dfrac{-1}{5}\times{2} \end{bmatrix} \\
A^{-1} &= \begin{bmatrix} \dfrac{2}{5} & \dfrac{1}{5} \\[6pt] \dfrac{1}{5} & \dfrac{-2}{5} \end{bmatrix}
\end{align*}

Now that we have $A^{-1}$, all we need to do is to multiply this matrix to $B$.
\begin{align*}
X &= A^{-1}\times{B} \\
X &= \begin{bmatrix} \dfrac{2}{5} & \dfrac{1}{5} \\[6pt] \dfrac{1}{5} & \dfrac{-2}{5} \end{bmatrix} \times \begin{bmatrix} 4 \\ -3 \end{bmatrix}  \\[2pt]
X &= \begin{bmatrix} \dfrac{2}{5}\times{4} + \dfrac{1}{5}\times{-3} \\[6pt]  \dfrac{1}{5}\times{4} + \dfrac{-2}{5}\times{-3} \end{bmatrix} \\
X &= \begin{bmatrix} \dfrac{8}{5} + \dfrac{-3}{5} \\[6pt] \dfrac{4}{5} + \dfrac{6}{5} \end{bmatrix} \\[2pt]
X &= \begin{bmatrix} \dfrac{8 - 3}{5} \\[6pt] \dfrac{4 + 6}{5} \end{bmatrix} \\[2pt]
X &= \begin{bmatrix} \dfrac{5}{5} \\[6pt] \dfrac{10}{5} \end{bmatrix} \\[2pt]
X &= \begin{bmatrix} 1 \\ 2 \end{bmatrix}
\end{align*}

Therefore, $x = 1$ and $y = 2$. I will encourage you to verify this using standard methods of solving two equations in two variables.

\clearpage\newpage
*** Cramer's Rule
Let $AX = B$ be a system of equations such that $A$ is the coefficients matrix, $X$ the matrix of unknowns, and $B$ the matrix of constants. For the sake of simplicity, we consider a $2\times{2}$ linear equation system.

\begin{align*}
a_{1}x + b_{1}y &= c_1 \\
a_{2}x + b_{2}y &= c_2
\end{align*}

Therefore, $A = \begin{bmatrix} a_1 & b_1 \\ a_2 & b_2 \end{bmatrix}$, $X = \begin{bmatrix} x \\ y \end{bmatrix}$, and $B = \begin{bmatrix} c_1 \\ c_2 \end{bmatrix}$.

Cramer's rule says that the solution to this system is as follows:

\begin{align*}
x &= \frac{D_{x}}{|A|} \\
y &= \frac{D_{y}}{|A|}
\end{align*}

where $D_x = \begin{vmatrix} c_1 & b_1 \\ c_2 & b_2 \end{vmatrix}$ and $D_y = \begin{vmatrix} a_1 & c_1 \\ a_2 & c_2 \end{vmatrix}$.

An example:

\begin{align*}
x + y &= 5 \\
2x - y &= 1
\end{align*}

We need to write down the three determinants that we need to compute $x$ and $y$.
It will help if you can list down all the elements you need for this exercise.
$a_1 = 1$, $b_1 = 1$, $c_1 = 5$, $a_2 = 2$, $b_2 = -1$, and $c_2 = 1$.
\begin{itemize}
\item $|A| = \begin{vmatrix} 1 & 1 \\ 2 & -1 \end{vmatrix} = -3$
\item $D_x = \begin{vmatrix} 5 & 1 \\ 1 & -1 \end{vmatrix} = -6$
\item $D_y = \begin{vmatrix} 1 & 5 \\ 2 & 1 \end{vmatrix} = -9$
\end{itemize}

Now that we have all the terms, we can calculate $x$ and $y$.
\begin{align*}
x &= \frac{D_x}{|A|} = \dfrac{-6}{-3} = 2 \\
y &= \frac{D_y}{|A|} = \dfrac{-9}{-3} = 3
\end{align*}
